### ISSUE TITLE
Unable to run python example

### ISSUE THREAD

**Issue by cburgmer** [phuang/ibus-tmpl#1]
/tmp/ibus-tmpl/engine$ python main.py
Traceback (most recent call last):
  File "main.py", line 79, in <module>
    main()
  File "main.py", line 76, in main
    launch_engine()
  File "main.py", line 47, in launch_engine
    IMApp().run()
  File "main.py", line 36, in **init**
    self.**engine = factory.EngineFactory(self.__bus)
  File "/tmp/ibus-tmpl/engine/factory.py", line 43, in __init**
    super(EngineFactory, self).**init**(self.**info, engine.Engine, ENGINE_PATH, bus, FACTORY_PATH)
TypeError: __init**() takes exactly 2 arguments (6 given)

**Comment by phuang** [comment]
Fixed
